[project]
name = "agent-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "unknown", email = "3517142071@qq.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
agent-dev = "agent_dev:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
